### ISSUE TITLE
BlackWidow Chroma V2

### ISSUE THREAD

**Issue by Kusoneko** [Martchus/blackwidowcontrol#3]
I'm not sure where exactly to put this, but, I tried modifying the script to include my BlackWidow Chroma V2 (device id 0x0221) in it, and it appears to work, unfortunately, I can't tell if it really does work as I have no macros set up on the macro keys and don't know how exactly I'm supposed to set that up. However, doing `sudo blackwidowcontrol -i` returned the following:

```
Found device: Black Widow Chroma V2
Kernel driver active; detaching it
Claiming interface
Sending initiation command
Data sent successfully
Releasing claimed interface
Reattaching the kernel driver
Done.
```

implying that it does somewhat work. I'll include my modified version of the script as an attachment, but as I don't have any macros set up I can't properly test it. (I added the extension .txt cause it wouldn't let me attach it otherwise.)
[blackwidowcontrol.txt](https://github.com/Martchus/blackwidowcontrol/files/3963056/blackwidowcontrol.txt)

**Comment by Kusoneko** [comment]
So, I tried adding a shortcut in my window manager that uses one of the macro keys as a hotkey, and it seems to work with each of the 5 macro keys.

**Comment by Martchus** [comment]
Thanks for extending the script. However, I've just `diff`ed your version of the script. Even when replacing the white-spaces again with tabs there are quite some unrelated changes. Can you provide a PR? And please don't change the indentation as it makes the diff completely useless.

But of course it makes sense to check whether the changes actually make a difference. Unfortunately the log including the line `Data sent successfully` means only that the data could be sent successfully. It doesn't mean that the *right* data has been sent correctly. If you can assign the macro keys as hotkeys that's of course already a good sign. However, have you tried whether that would even work without running the script after just plugging the keyboard? Only if that doesn't work the execution of the script made a difference and we know it works.

By the way, setting up macros is out of the scope of this script anyways. It merely aims to enable the macro keys to you can assign hotkeys to it like you've just did or use them with `xmacro` or similar tools.

**Comment by Kusoneko** [comment]
I kinda forgot about this, but I haven't run the script since and just tried setting hotkeys to each of the 5 macro keys as I did previously, and it appears to work without the script at all, implying that it wasn't necessary to begin with, so a PR won't be necessary as the script likely does not make any difference in whether or not the macro keys work.
