### ISSUE TITLE
Key not identifying

### ISSUE THREAD

**Issue by Max604** [Martchus/blackwidowcontrol#9]
Hello,

I'm having some issues with making this work. I couldn't find many instructions about how to remap the macro keys.

From the code below, it seems all good and working, however. I'm not sure where to go from here. When I listen to key presses, the macro keys aren't showing up as being pressed.

Where do I go from here? 
```
MBP blackwidowcontrol % sudo python3 blackwidowcontrol.py
Password:
Found device: Black Widow Chroma V2
Kernel driver active; detaching it
Claiming interface
Releasing claimed interface
Reattaching the kernel driver
```

**Comment by Martchus** [comment]
I think you need to pass the `-i` parameter to initialize the functionality of macro keys. Use `--help` to see all available options.

**Comment by Max604** [comment]
I also tried with the -i too

**Comment by Martchus** [comment]
Then I suppose your exact keyboard model or firmware version is not supported. According to some contributor "Black Widow Chroma V2" works so it mentioned in the README. Maybe that's not the case after all or some firmware update changed that. Unfortunately I cannot provide further support for this. Looking at https://github.com/openrazer/openrazer is likely a good idea at this point anyways.

**Comment by Max604** [comment]
Ah okay,

Thanks so much! Unfortunately openrazer isn't supported for mac.

Sent via Superhuman ( ***@***.*** )

**Comment by Martchus** [comment]
I highly doubt anybody has using this script on Mac as well. Maybe that's why it isn't working. I'm closing this issue now because I doubt I can help you and since you're using a Mac that's not supported/tested anyways.
